# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0a9ab4106efbc4a93ac371ca584b2f3cc7b9ec5d15e01da1b649d1ad90dae7fc37e34f2d0e954189f2d09d9f0ca6ec5120c65947fe204ffed7206eff4e0fc64

test:
  secret_key_base: e6dac6578eb0df62b8bd58d06b8c789bb512fcd45584d00234ab40dbf683d6625ddf0b364c776b00c95c7c37e6e519e1339cad8d5de8f7a3a13e46e18ce4ff90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
